retrievabl/urls.py
from django.urls import path
from . import views


app_name = 'retrievabl'
urlpatterns = [
    path('', views.index, name='index'),
    path('?q=<str:query>&neg=<int:neg>', views.ArticleListView.as_view(), name='search'),
    path('our_mission/', views.mission, name='our_mission'),
    path('contact_us/', views.contact, name='contact_us'),
]

website/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('retrievabl.urls')),
]

retrievabl/models.py
from django.db import models


class Article(models.Model):
    title = models.CharField(max_length=100)
    body = models.TextField()
    body_preview = models.CharField(max_length=300)
    url = models.TextField()
    source = models.CharField(max_length=75)
    score = models.DecimalField(max_digits=15, decimal_places=3)
    percentage = models.DecimalField(max_digits=15, decimal_places=2)

    def get_preview(self):
        return self.body[:300]

    def __str__(self):
        return self.title + ": " + self.body_preview


class Search(models.Model):
    query = models.CharField(max_length=100)
    neg = models.IntegerField(choices=((1, "Neg. Filtering"), (0, "Reg. BM25")), default=1)
    ndcg = models.DecimalField(max_digits=15, decimal_places=3)

retrievabl/forms.py
from django import forms
from .models import Search


class ArticleSearchForm(forms.ModelForm):
    class Meta:
        CHOICES = [('select1', 'select 1'),
                   ('select2', 'select 2')]
        model = Search
        fields = [
            'query', 'neg'
        ]
        widgets = {
            'query': forms.TextInput(attrs={'placeholder': 'Search for news'}),
            'neg': forms.RadioSelect(choices=CHOICES)
        }

retrievabl/views.py
import os

from django.shortcuts import render, reverse
from django.conf import settings
from .forms import ArticleSearchForm
from django.views.generic.list import ListView
from django.views.generic.detail import SingleObjectMixin
from .models import Article, Search
from math import log2
from django.http import HttpResponseRedirect
import string
import re

neg_words = ['aggravated', 'agitated', 'alarmed', 'anger', 'angered', 'angry', 'anguish', 'antipathy', 'anxiety',
             'anxious', 'apprehension', "aren't", 'aversion', 'bad', 'befuddled', 'bewildered', 'bitterness', 'break',
             'broken', 'cannot', "can't", 'conceited', 'confound', 'confused', 'contempt', 'coward', 'crammed',
             'decrepit', 'deflated', 'dejected', 'deny', 'denied', 'depressed', 'desperate', 'despondent', "didn't",
             'disappointed', 'discombobulated', 'discomposed', 'disconcert', 'discontented', 'disgruntled', 'disgust',
             'disillusioned', 'dislike', 'dismayed', 'dispirited', 'displeasure', 'dissatisfied', 'distraught',
             'distressed', "doesn't", 'dread', 'embarrassed', 'enraged', 'envy', 'exasperated', 'excited', 'exploit',
             'fail', 'failure', 'fear', 'ferocious', 'flustered', 'fractious', 'frantic', 'frenzied', 'frenzy',
             'frightful', 'frightened', 'frustrated', 'fuddle', 'furious', 'gloomy', 'glumness', 'grievous', 'grouchy',
             'grumpy', 'guilty', "hadn't", "hasn't", "haven't", 'heartbroken', 'homesickness', 'hopeless', 'horrified',
             'horror', 'hostility', 'humiliated', 'hysterical', 'inconsolable', 'indignant', 'irritated', "isn't",
             'jealousy', 'jolted', 'lazy', 'livid', 'loathing', 'loneliness', 'mad', 'maddened', 'manic', 'melancholic',
             'miserable', 'misery', 'mortified', "mustn't", "needn't", 'nervous', 'no', 'nosy', 'outrage',
             'outraged', 'outrageous', 'overwrought', 'panicked', 'peculiar', 'perplexed', 'phrenetic', 'picky', 'rage',
             'regret', 'regretful', 'remorse', 'remorseful', 'resent', 'resentment', 'revulsion', 'sad', 'sadly',
             'sadness', 'scared', 'scary', 'scorn', 'shocked', "shouldn't", 'sorrowful', 'spite', 'stingy', 'stubborn',
             'stunned', 'tense', 'tenseness', 'terrified', 'terror', 'torment', 'uneasiness', 'upset', 'vengefulness',
             "wasn't", "weren't", 'wild', 'woeful', "won't", 'worried', "wouldn't", 'wrath', 'wretched'
             ]


def index(request):
    form = ArticleSearchForm()
    if 'query' and 'neg' in request.GET:
            return HttpResponseRedirect(reverse('retrievabl:search', kwargs={'query': request.GET['query'],
                                                                             'neg': request.GET['neg']}))
    return render(request, 'retrievabl/index.html', {'form': form})


def search(request):
    form = ArticleSearchForm()
    if 'query' in request.GET:
        query = request.GET['query']
        return HttpResponseRedirect('/search/' + query)
    return render(request, 'retrievabl/search.html', {'form': form})


def mission(request):
    form = ArticleSearchForm()
    if 'query' in request.GET:
        query = request.GET['query']
        return HttpResponseRedirect('/search/' + query)
    return render(request, 'retrievabl/our_mission.html', {'form': form})


def contact(request):
    form = ArticleSearchForm()
    if 'query' in request.GET:
        query = request.GET['query']
        return HttpResponseRedirect('/search/' + query)
    return render(request, 'retrievabl/contact_us.html', {'form': form})


def avg_doc_len(corpus):
    totlen = 0
    translator = str.maketrans('', '', string.punctuation)
    for doc in corpus:
        dbody = str(doc.body.lower().split()).translate(translator)
        length = len(re.findall(r'\w+', dbody))
        totlen += length
    avg = totlen / len(corpus)
    return avg


def neg_score(query, corpus):
    translator = str.maketrans('', '', string.punctuation)
    nw = neg_words
    query = query.lower()
    negbm25score = 0
    k = 1.25
    nk = 10 # weight for negative filtering
    avgdl = avg_doc_len(corpus)
    M = len(corpus)
    b = 0.75
    docfreq = {}
    freq = 0
    for doc in corpus:
        find_neg(doc)
        for word in query.lower().split():
            if word in str(doc.body.lower().split()).translate(translator):
                freq += 1
        docfreq[str(word).lower()] = freq
        freq = 0

    result = 0
    regbm25score = 0.0
    for doc in corpus:
        dbody = str(doc.body.lower().split()).translate(translator)
        length = len(re.findall(r'\w+', dbody))
        for word in query.split():
            if word in dbody:
                one = query.count(word.lower())
                two = (k + 1) * dbody.count(str(word).lower())
                three = dbody.count(str(word).lower()) + (k * (1 - b + (b * (length / avgdl))))
                four = log2((M + 1) / (doc.body.count(str(word)) + 1))
                result = one * (two / three) * four
                regbm25score += result

        result = (1 - ((doc.percentage / 100) * nk)) * regbm25score
        negbm25score = result
        doc.score = float(negbm25score)
        doc.save()
        negbm25score = 0.0
        regbm25score = 0.0


def reg_score(query, corpus):
    translator = str.maketrans('', '', string.punctuation)
    query = query.lower()
    regbm25score = 0
    k = 1.25
    avgdl = avg_doc_len(corpus)
    M = len(corpus)
    b = 0.75
    docfreq = {}
    freq = 0
    for doc in corpus:
        find_neg(doc)
        for word in query.lower().split():
            if word in str(doc.body.split()).translate(translator):
                freq += 1
        docfreq[str(word).lower()] = freq
        freq = 0
    for doc in corpus:
        dbody = str(doc.body.lower().split()).translate(translator)
        length = len(re.findall(r'\w+', dbody))
        for word in query.split():
            if word in dbody:
                    one = query.count(word.lower())
                    two = (k + 1) * dbody.count(str(word).lower())
                    three = dbody.count(str(word).lower()) + (k * (1 - b + (b * (length / avgdl))))
                    four = log2((M + 1) / (doc.body.count(str(word)) + 1))
                    result = one * (two / three) * four
                    regbm25score += result
        doc.score = float(regbm25score)
        doc.save()
        regbm25score = 0.0


def find_neg(doc):
    translator = str.maketrans('', '', string.punctuation)
    nw = neg_words
    neg_count = 0
    dbody = str(doc.body.lower().split()).translate(translator)
    for neg_word in nw:
        find = len(re.findall(str(neg_word), dbody))
        if find > 0:
            neg_count += find
    length = len(re.findall(r'\w+', dbody))
    doc.percentage = float(100 * (neg_count / length))
    doc.save()


class ArticleListView(ListView):
    template_name = 'retrievabl/search.html'
    context_object_name = 'articles'

    def get_ndcg(self, query):
        neg_score(query, Article.objects.all())
        articles = Article.objects.order_by('score').reverse().filter(score__gt=0)
        i = 1
        dcg = 0
        idcg = 0
        for article in articles:
            dcg += float(2 ** article.score - 1) / log2(i + 1)
            i += 1

        reg_score(query, Article.objects.all())
        articles = Article.objects.order_by('score').reverse().filter(score__gt=0)
        i = 1
        for article in articles:
            idcg += float(2 ** article.score - 1) / log2(i + 1)

        if idcg == 0:
            idcg = 1

        return float(dcg / idcg)

    def get_queryset(self):
        query = self.kwargs.pop('query', None)
        neg_rank = self.kwargs.pop('neg', None)

        if neg_rank == 1:
            neg_score(query, Article.objects.all())
        else:
            reg_score(query, Article.objects.all())

        result = Article.objects.order_by('score').reverse().filter(score__gt=0)
        return result

retrievabl/templates/retrievabl/article_list.html
{% extends 'retrievabl/base_page.html' %}
{% load static %}

<!-- Referenced django documentation for detailview:
     https://docs.djangoproject.com/en/3.0/ref/class-based-views/generic-display/ -->

{% block content %}

{% endblock %}

retrievabl/templates/retrievabl/base_page.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Jekyll v3.8.6">
    <title>Retrievabl</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.4/examples/starter-template/">

    <!-- Bootstrap core CSS -->
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">

    <!-- Favicons -->
<link rel="apple-touch-icon" href="/docs/4.4/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
<link rel="icon" href="/docs/4.4/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
<link rel="icon" href="/docs/4.4/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
<link rel="manifest" href="/docs/4.4/assets/img/favicons/manifest.json">
<link rel="mask-icon" href="/docs/4.4/assets/img/favicons/safari-pinned-tab.svg" color="#563d7c">
<link rel="icon" href="/docs/4.4/assets/img/favicons/favicon.ico">
<meta name="msapplication-config" content="/docs/4.4/assets/img/favicons/browserconfig.xml">
<meta name="theme-color" content="#563d7c">


    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        -ms-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }
    </style>
    <link rel="stylesheet" href="{% static 'retrievabl/base.css' %}">

  </head>

<body>
  {% block navbar %}
    <nav class="d-flex navbar navbar-expand-md navbar-light bg-light fixed-top align-items-center">
        <a class="navbar-brand" href="{% url 'retrievabl:index' %}">
            <img style="margin-left:6px;" src="{% static 'retrievabl/images/Retrievabl.png' %}" alt="Retrievabl">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-center" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
            </ul>
            <ul class="navbar-nav px-3">
                <button type="donate" class="nav-btn btn btn-success my-2 my-sm-0">Donate</button>
            </ul>
        </div>

    </nav>
  {% endblock %}



{% block content %}
    {{content}}
    {% endblock %}

{% block footer %}
  <footer class="footer">
      <p class="float-right"><a class="footer-item">©Kaitlyn Randolph</a></p>
      <p><a class="footer-item" href="{% url 'retrievabl:our_mission' %}">Our Mission</a> <a class="footer-item" href="{% url 'retrievabl:contact_us' %}">Contact Us</a></p>

    </footer>
  {% endblock %}

    <!-- FOOTER -->
  <!-- <footer class="container">
    <p class="float-right"><a href="#">Back to top</a></p>
    <p>&copy; 2017-2019 Company, Inc. &middot; <a href="#">Privacy</a> &middot; <a href="#">Terms</a></p>
  </footer> -->


    <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
</body>

retrievabl/templates/retrievabl/contact_us.html
{% extends 'retrievabl/base_page.html' %}
{% load static %}

{% block content %}
    <link rel="stylesheet" href="{% static 'retrievabl/contact.css' %}">
    <div class="d-flex container-fluid header-box align-items-center">
        <h2 class="header-title">Contact Us</h2>
    </div>
    <main role="main" class="container">
        <div class="form-group contact-line" style="clear:both;">
            <label for="contact-box"><h3>We'd love to hear from you!</h3></label>
            <textarea class="form-control contact-box" id="contact-box" rows="3"></textarea>
            <button class="nav-btn btn btn-primary my-2 my-sm-0 contact-btn float-right" type="submit">Submit</button>
        </div>
    </main>
{% endblock %}

retrievabl/templates/retrievabl/index.html
{% extends 'retrievabl/base_page.html' %}
{% load static %}

{% block navbar %}

{% endblock %}

{% block content %}
<link rel="stylesheet" href="{% static 'retrievabl/index.css' %}">
<main role="main" class="container">
  <div class="welcome" style="width: 50% margin: 0;">
       <img style="margin-left:6px; margin-top:15%; height: auto" src="{% static 'retrievabl/images/Welcome.png' %}" alt="Welcome to Retrievabl">
      <form class="form-inline" method="get">
            {{ form.neg }}
            {{ form.query }}
            <button class="nav-btn btn btn-primary my-2 my-sm-0" type="submit">Search</button>
      </form>
    <p class="donate-msg">Retrievabl is funded in part by donations from users. Please consider donating.</p>
      <button type="donate" class="btn btn-success btn-lg" style="margin-top: 10px;">Donate</button>
  </div>

</main>
    {% endblock %}

retrievabl/templates/retrievabl/our_mission.html
{% extends 'retrievabl/base_page.html' %}
{% load static %}

{% block content %}
<link rel="stylesheet" href="{% static 'retrievabl/mission.css' %}">
    <div class="d-flex container-fluid mission-box align-items-center">
        <h2 class="mission-title">Our Mission</h2>
    </div>
    <p class="mission">Here at Retrievabl, we want to give more transparency to news searching. We hope to give you a
clearer view of the news you are consuming by giving you information about why our search results
are ranked the way they are. We have based our search algorithm off the idea that overly-negative news
        has a <a href="https://www.verywellmind.com/negative-bias-4589618">large impact on how people think about key topics</a>
        covered in news articles. We hope that by improving the visibility of less-negative news articles,
        we can make a positive impact on society. </p>
{% endblock %}

retrievabl/templates/retrievabl/search.html
{% extends 'retrievabl/base_page.html' %}
{% load static %}

{% block navbar %}
    <nav class="d-flex navbar navbar-expand-md navbar-light bg-light fixed-top align-items-center">
        <a class="navbar-brand" href="{% url 'retrievabl:index' %}">
            <img style="margin-left:6px;" src="{% static 'retrievabl/images/Retrievabl.png' %}" alt="Retrievabl">
        </a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse justify-content-center" id="navbarCollapse">
            <ul class="navbar-nav mr-auto">
            </ul>
            <ul class="navbar-nav px-3">
                <button type="donate" class="nav-btn btn btn-success my-2 my-sm-0">Donate</button>
            </ul>
        </div>

    </nav>
  {% endblock %}

{% block content %}
    <link rel="stylesheet" href="{% static 'retrievabl/search.css' %}">
    <p>{{ Search.ndcg }}</p>
    <ul class="articles">
    {% for article in articles %}
        <li style="list-style-type: none;"><div class="card" style="width: 50%; margin-bottom: 5px; margin-right: 0;">
            <div class="card-body">
                <h6 class="card-title"><a href="{{ article.url }}"><b>{{ article.title }}</b></a></h6>
                <h7 class="card-subtitle mb-2 text-muted">{{ article.source }} • {{ article.url }}</h7>
                <p class="card-text">{{ article.body_preview }}...</p>
                <h6 style="float:right;">| Score: {{ article.score }} </h6>
                <h6 style="float:right;">Negative words: {{ article.percentage }}% |</h6>
            </div>
        </div>

        </li>

    {% empty %}
        <p>No results found for given query.</p>
    {% endfor %}
    </ul>
{% endblock %}